[project]
name = "notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair[all]>=6.2.2",
    "boto3>=1.43.62",
    "botocore[crt]>=1.43.62",
    "imbalanced-learn>=0.14.2",
    "marimo>=0.23.16",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "polars>=1.43.2",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
]
